version: '3.1'

services:
    web:
        container_name: workshop_webapi_container
        build: ./app
        expose:
          - "8080"
        volumes:
            - ./app:/app
        command: /usr/local/bin/gunicorn --workers 5 --worker-class eventlet --bind :8080 -m 007 src.app:app
        
    nginx:
        container_name: workshop_nginx_container
        build: ./nginx
        ports:
          - "5000:80"
        depends_on:
          - web